// Generated by https://pagedraw.io/pages/11695
import React from 'react';
import './com.css';


function render() {
    return <div className="com-com-3">
        <div className="com-0">
            <input type="text" placeholder="Placeholder" className="com-text_input-0" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
