// Generated by https://pagedraw.io/pages/11695
import React from 'react';
import './component.css';


function render() {
    return <div className="pd33919483452931987-component-3">
        <div className="pd33919483452931987-0">
            <input type="text" placeholder="Placeholder" className="pd33919483452931987-text_input-0" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
