// Generated by https://pagedraw.io/pages/11687
import React from 'react';
import './component_1.css';


function render() {
    return <div className="component_1-component_1">
        <div className="component_1-0">
            <input type="text" placeholder="Placeholder" className="component_1-text_input-5" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
