// Generated by https://pagedraw.io/pages/11695
import React from 'react';
import './component_.css';


function render() {
    return <div className="component_-component_-3">
        <div className="component_-0">
            <input type="text" placeholder="Placeholder" className="component_-text_input-0" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
