// Generated by https://pagedraw.io/pages/11528
import React from 'react';
import './frame.css';


function render() {
    return <div className="frame-frame-0">
        <div className="frame-0">
            <div className="frame-rectangle-0">
                <div className="frame-0-0-0">
                    <div className="frame-0-0-0-0">
                        <div className="frame-0-0-0-0-0">
                            <div className="frame-0-0-0-0-0-0">
                                <div className="frame-vector-0" /> 
                                <div className="frame-vector-000">
                                    <div className="frame-0-0-0-0-0-0-1-0">
                                        <div className="frame-vector-00" /> 
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="frame-0-0-0-1">
                        <div className="frame-0-0-0-1-0">
                            <div className="frame-vector-0000" /> 
                        </div>
                    </div>
                    <div className="frame-0-0-0-2">
                        <div className="frame-0-0-0-2-0">
                            <div className="frame-vector-00000" /> 
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
