// Generated by https://pagedraw.io/pages/11528
import React from 'react';
import './rectangle_3.css';


function render() {
    return <div className="rectangle_3-rectangle_3-0">
        <div className="rectangle_3-0">
            <div className="rectangle_3-rectangle_3" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
