// Generated by https://pagedraw.io/pages/11695
import React from 'react';
import './te.css';


function render() {
    return <div className="te-te-3">
        <div className="te-0">
            <input type="text" placeholder="Placeholder" className="te-text_input-0" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
