// Generated by https://pagedraw.io/pages/11695
import React from 'react';
import './text.css';


function render() {
    return <div className="text-text-3">
        <div className="text-0">
            <input type="text" placeholder="Placeholder" className="text-text_input-0" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
