// Generated by https://pagedraw.io/pages/11695
import React from 'react';
import './textare.css';


function render() {
    return <div className="textare-textare-3">
        <div className="textare-0">
            <input type="text" placeholder="Placeholder" className="textare-text_input-0" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
