// Generated by https://pagedraw.io/pages/11695
import React from 'react';
import './textarea.css';


function render() {
    return <div className="textarea-textarea-3" /> ;
};

export default function(props) {
    return render.apply({props: props});
}
