// Generated by https://pagedraw.io/pages/11695
import React from 'react';
import './texta.css';


function render() {
    return <div className="texta-texta-3">
        <div className="texta-0">
            <input type="text" placeholder="Placeholder" className="texta-text_input-0" /> 
        </div>
    </div>;
};

export default function(props) {
    return render.apply({props: props});
}
